name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: |
        docker build -t flask_server:latest .

    - name: Deploy Docker container
      run: |
        docker run -d -p 80:80 --name flask_server flask_server:latest

    - name: Wait for server to start
      run: sleep 10

    - name: Test server
      run: |
        if curl --fail http://localhost:80; then
          echo ""
          echo "Server is up and running"
        else
          echo ""
          echo "Server is not responding"
          exit 1
        fi